FROM python:3.10

ENV VIRTUAL_ENV /env
ENV PATH $VIRTUAL_ENV/bin:$PATH
ENV PYTHON_VERSION 3.10

ADD main.py /app/
WORKDIR /app

RUN pip install virtualenv
RUN virtualenv $VIRTUAL_ENV -p python$PYTHON_VERSION
RUN . activate
RUN pip install psutil
