apiVersion: v1
kind: Pod
metadata:
  name: my-redis
spec:
  containers:
  - image: redis
    name: redis-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /datacache
      type: Directory
