apiVersion: v1
kind: Pod
metadata:
  name: my-redis
spec:
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
  containers:
  - image: redis
    name: redis-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
