apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.22.1
    resources:
      requests:
         memory: 100Mi
         cpu: “0.5”
      limits:
        memory: 200Mi
        cpu: “1”
  ports:
  - containerPort: 80
