apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "privileged"
      audit: "privileged"
      warn: "privileged"
    exemptions:
      usernames: [ “user1”, “user2” ]
      namespaces: [ “ns1”, ”ns2” ]
