apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-persistent-volume-claim
        livenessProbe:
          exec:
            command:
              - /usr/bin/mongo
              - --eval
              - db.serverStatus()
          initialDelaySeconds: 10
          timeoutSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-volume-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi