apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /tmpdata
    server: 172.72.1.2
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
