apiVersion: v1
kind: Pod
metadata:
  name: demo-configmap-as-env-variable
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: port
      envFrom:
        - configMapRef:
            name: tier-config
  restartPolicy: Never