apiVersion: v1
kind: Pod
metadata: 
  name: demo-secrets-via-volume-basic
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "cat /etc/config/username" ]
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/config"
  volumes:
    - name: config-volume
      secret:
        secretName: app-secrets 
