apiVersion: v1
kind: Pod
metadata:
  name: demo-secrets-as-env-variable
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: Username
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: username
        - name: Password
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: password
      
  restartPolicy: Never